name: dio_range_download
description: A download tool library that supports resumable downloading and segmented downloading.
version: 1.0.0
homepage: https://github.com/qiaoshouqing/dio_range_download

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^4.0.0

dev_dependencies:
  test: ^1.5.1
  pedantic: ^1.8.0
  test_coverage: ^0.4.1